blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/JotaRandom/apt-pac/discussions/new?category=q-a
    about: Please ask questions in our Discussions area
